name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem, not just the solution you have in mind.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
  - type: checkboxes
    id: help
    attributes:
      label: Would you be willing to work on this?
      options:
        - label: I'd be happy to open a PR
